### PR TITLE
Add Swift versions of test case parsing code

### LINKED ISSUE #303: Linux test cases aren't parsed correctly
It seems xcpretty is expecting Objective-C method names in test case results, even for Swift tests:

```
Test Case '[SyntaxTests.SyntaxTestRunner testSyntax]' passed (3.104 seconds)
```

But on Linux, the Objective-C names aren't reported -- we get Swift names:

```
Test Case 'SyntaxTestRunner.testSyntax' passed (3.104 seconds)
```

I think we need to teach xcpretty to also parse Swift names.

I'm playing with this on a branch now.

### PR DESCRIPTION
**Pull request by harlanhaskins**
Because `swift test` on Linux prints Swift method names instead of
Objective-C method names, we needed to update the test case parser to
handle Swift names.

This also adds test cases for common Swift method names to match the
Objective-C ones.

I did a manual test on Linux and it works there, but I don't know how to really automate this beyond specially crafted Swift input.

Fixes #303

### CODE REVIEW

**Comment by harlanhaskins** [comment]
There we go!

**Comment by harlanhaskins** [comment]
@supermarin Any chance we could pick this back up?

**Comment by supermarin** [comment]
let me look at it tomorrow, thanks!

**Comment by zayass** [comment]
what about FAILING_TEST_MATCHER?

**Comment by yonaskolb** [comment]
Would love to see this moved forward! 👍

**Comment by kmahar** [comment]
+1 for moving this forward, would be very useful to my team 🙂

**Pull request closed without merging**
